In [1]:
import numpy as np
import sympy as sp
import numpy.linalg as la

def solve( A, b ):
    n = b.size
    b = np.array(b,float)
    for i in range(1,n):
        b[i]=b[i] - np.dot(A[i,:i],b[:i])
    for k in range(n-1,-1,-1):
        b[k] = (b[k] - np.dot(A[k,k+1:n],b[k+1:n]))/A[k,k];

    return b

def LU_decomposition(A):
    n = len(A)
    L = np.zeros((n,n))
    U = np.zeros((n,n))
    for j in range(n):
        L[j][j] = 1

        for i in range(j+1):
            s1 = 0
            for k in range(i):
                s1 += U[k][j] * L[i][k]
            U[i][j] = A[i][j] - s1

        for i in range(j, n):
            s2 = 0
            for k in range (j):
                s2 += U[k][j] * L[i][k]
            L[i][j] = (A[i][j] - s2) / U[j][j]

    return (L,U)

def MatrixInverse(A):
    L, U = LU_decomposition(A)
    N = len(A)
    X = np.zeros((N,N))
    for i in range(0, N):
        e = np.zeros(N)
        e[i] = 1

        y = solve(L, e)
        x = solve(U, y)

        for j in range(0, N):
            X[j][i] = x[j]
    return (X)

A = np.array([ [1, 1, 1], [0, 1, 2], [7, 1, 4] ])

print("\nA:")
print(A)
print("\ninverse A:")
print(MatrixInverse(A))

print("\n\nreal inverse A:")
print(la.inv(A))






A:
[[1 1 1]
 [0 1 2]
 [7 1 4]]

inverse A:
[[ 0.22222222 -0.33333333  0.11111111]
 [ 1.55555556 -0.33333333 -0.22222222]
 [-0.77777778  0.66666667  0.11111111]]


real inverse A:
[[ 0.22222222 -0.33333333  0.11111111]
 [ 1.55555556 -0.33333333 -0.22222222]
 [-0.77777778  0.66666667  0.11111111]]
