In [4]:
import sympy as sp
import numpy as np
import numpy.linalg as la

def LU_decomposition(A):
    n = len(A)
    L = np.zeros((n,n))
    U = np.zeros((n,n))

    for j in range(n):
        L[j][j] = 1

        for i in range(j+1):
            s1 = 0
            for k in range(i):
                s1 += U[k][j] * L[i][k]
            U[i][j] = A[i][j] - s1

        for i in range(j, n):
            s2 = 0
            for k in range (j):
                s2 += U[k][j] * L[i][k]
            L[i][j] = (A[i][j] - s2) / U[j][j]

    return (L,U)

def solve( A, b ):
    n = b.size
    b = np.array(b,float)
    for i in range(1,n):
        b[i]=b[i] - np.dot(A[i,:i],b[:i])
    for k in range(n-1,-1,-1):
        b[k] = (b[k] - np.dot(A[k,k+1:n],b[k+1:n]))/A[k,k];

    return b


A2 = np.array([[2., -1., 0.], [-1., 2., -1.], [1e-16, 1., -1.]])
b2 = np.array([1., 0., 0.])
L, U = LU_decomposition(A2)

#A3 =  sp.Matrix([[2., -1., 0.], [-1., 2., -1.], [1e-16, 1., -1.]])
#b3 = sp.Matrix([1., 0., 0.])
#L2, U2, _ = A3.LUdecomposition()

y = solve(L,b2)
x = solve(U,y)
#print("L2 matrix:\n",L2)
#print("\nU2 matrix:\n",U2)

print("L matrix:\n",L)
print("\nU matrix:\n",U)
print("\nРешение СЛАУ:",x)


L matrix:
 [[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-5.00000000e-01  1.00000000e+00  0.00000000e+00]
 [ 5.00000000e-17  6.66666667e-01  1.00000000e+00]]

U matrix:
 [[ 2.         -1.          0.        ]
 [ 0.          1.5        -1.        ]
 [ 0.          0.         -0.33333333]]

Решение СЛАУ: [1. 1. 1.]
